apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: password-generator
rules:
- apiGroups: ["*"]
  resources: ["secrets", "events"]
  verbs: ["*"]
- apiGroups: ["exphost.pl"]
  resources: ["passwords"]
  verbs: ["*"]
