---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: password-generator
subjects:
- kind: ServiceAccount
  name: password-generator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: password-generator
  apiGroup: rbac.authorization.k8s.io
