apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: passwords.exphost.pl
spec:
  group: exphost.pl
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                copy_namespaces:
                  type: array
                  items:
                    type: string
                types:
                  type: array
                  items:
                    type: string
                    
  scope: Namespaced
  names:
    plural: passwords
    singular: password
    kind: Password
