apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregate-passwords-to-admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups: ["exphost.pl"]
  resources: ["passwords"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
