apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator
  labels:
    app: password-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-generator
  template:
    metadata:
      labels:
        app: password-generator
    spec:
      serviceAccount: password-generator
      containers:
        - name: renderer
          image: registry.gitlab.exphost.pl/exphost/password-generator:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
