apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: password-generator-podmonitor
  labels:
    app: password-generator
spec:
  podMetricsEndpoints:
  - interval: 5s
    port: metrics
  selector:
    matchLabels:
      app: password-generator
